import { publicProcedure } from '../../../create-context';
import { Club, ClubCategory } from '@/types/club';

// Real club data from the school spreadsheet - ALL 95 CLUBS
const REAL_CLUBS_DATA: Club[] = [
  {
    id: '1',
    name: '3D Printing and Animation Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Chris Meyer',
    presidentName: 'Pranav Vinod',
    presidentEmail: 'vinod2553@mydusd.org',
    email: 'vinod2553@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'N-108',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '2',
    name: 'Acts of Random Kindness Club',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Jason Morganstein',
    presidentName: 'Khang Fung',
    presidentEmail: 'fung9424@mydusd.org',
    email: 'fung9424@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'F-201',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '3',
    name: 'Aerospace Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Jeanne Morgan',
    presidentName: 'Sohail Kazi',
    presidentEmail: 'kazi1290@mydusd.org',
    email: 'kazi1290@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'F-305',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '4',
    name: 'Afghan Student Association',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Mike Ruegg',
    presidentName: 'Sahara Salemi',
    presidentEmail: 'salemi3165@mydusd.org',
    email: 'salemi3165@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-211',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '5',
    name: 'Animation Club',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Chris Meyer',
    presidentName: 'Tina Lin',
    presidentEmail: 'lin3225@mydusd.org',
    email: 'lin3225@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'N-108',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '6',
    name: 'Archery Club',
    description: '',
    category: 'Sports' as ClubCategory,
    tags: [],
    advisorName: 'Neilson Vuong',
    presidentName: 'Eujin Michelle Low',
    presidentEmail: 'low5021@mydusd.org',
    email: 'low5021@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: 'Every Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-204',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '7',
    name: 'Art Club',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Noel Sollom',
    presidentName: 'Emaan Qayyum and Ryan Cho',
    presidentEmail: 'qayyum1361@mydusd.org',
    email: 'qayyum1361@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'N-101',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '8',
    name: 'Asian Student Association',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Celine Shi',
    presidentName: 'Phoebe Yee & Yena Lee',
    presidentEmail: 'yee2852@mydusd.org',
    email: 'yee2852@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-204',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '9',
    name: 'AstroGaels',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Jon White',
    presidentName: 'Suraj R Kudrikar',
    presidentEmail: 'kudrikar1327@mydusd.org',
    email: 'kudrikar1327@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'F-304',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '10',
    name: 'BC2M',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Kelly Gambs',
    presidentName: 'Yashita Vijay',
    presidentEmail: 'vijay3568@mydusd.org',
    email: 'vijay3568@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-103',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '11',
    name: 'Best Buddies',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Lu Middleton',
    presidentName: 'Lexi Esquivel',
    presidentEmail: 'esquivel9503@mydusd.org',
    email: 'esquivel9503@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: 'Every Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-105',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '12',
    name: 'California Scholarship Federation (CSF)',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Kim Halket',
    presidentName: 'CJ Galang',
    presidentEmail: 'galang2959@mydusd.org',
    email: 'galang2959@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'Sports Complex',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '13',
    name: 'Cantonese Student Association',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Jaclyn Capie',
    presidentName: 'Audrey Tang',
    presidentEmail: 'tang2416@mydusd.org',
    email: 'tang2416@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-102',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '14',
    name: 'Chemistry Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Michael Correia',
    presidentName: 'Jonathan Song',
    presidentEmail: 'song5227@mydusd.org',
    email: 'song5227@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-203',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '15',
    name: 'CodeHers',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Mitsuka Bude',
    presidentName: 'Alicia Wang and Danica Truong',
    presidentEmail: 'wang0838@mydusd.org',
    email: 'wang0838@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'F-307',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '16',
    name: 'Data Science Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Matthew Janisch',
    presidentName: 'Ryan Lee',
    presidentEmail: 'lee2830@mydusd.org',
    email: 'lee2830@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-112',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '17',
    name: 'DHS 4 The Athletes',
    description: '',
    category: 'Sports' as ClubCategory,
    tags: [],
    advisorName: 'Tom Costello',
    presidentName: 'Tarun Tiwari',
    presidentEmail: 'tiwari5235@mydusd.org',
    email: 'tiwari5235@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'Weight Room',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '18',
    name: 'DHS Adopt a Family',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Brian Do',
    presidentName: 'Aanya Srivastava',
    presidentEmail: 'srivastava2784@mydusd.org',
    email: 'srivastava2784@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-210',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '19',
    name: 'DHS Avani',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Brittany Neideffer',
    presidentName: 'Rithika Lakshmi',
    presidentEmail: 'lakshmi6820@mydusd.org',
    email: 'lakshmi6820@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: 'Every Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-210',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '20',
    name: 'DHS Biology Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Erica Lee',
    presidentName: 'Brianna Huang',
    presidentEmail: 'huang3012@mydusd.org',
    email: 'huang3012@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-105',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '21',
    name: 'DHS ChangeMakers',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Silvia Sosa',
    presidentName: 'Hasini Shivakumar',
    presidentEmail: 'Shivakumar3443@mydusd.org',
    email: 'Shivakumar3443@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-108',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '22',
    name: 'DHS FCSN',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Dan Poulos',
    presidentName: 'Joshua Wu',
    presidentEmail: 'wu2886@mydusd.org',
    email: 'wu2886@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-102',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '23',
    name: 'DHS Game Development Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Chris Meyer',
    presidentName: 'Pranav Peethani',
    presidentEmail: 'peethani2813@mydusd.org',
    email: 'peethani2813@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'N-108',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '24',
    name: 'DHS Lego Club',
    description: '',
    category: 'Hobbies' as ClubCategory,
    tags: [],
    advisorName: 'Brian Do',
    presidentName: 'Jack Zhou',
    presidentEmail: 'zhou7162@mydusd.org',
    email: 'zhou7162@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: 'Every Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-210',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '25',
    name: 'DHS Math Club',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Elena Tigner',
    presidentName: 'Sophia Henningsen',
    presidentEmail: 'henningsen3629@mydusd.org',
    email: 'henningsen3629@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-208',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '26',
    name: 'DHS Photography Club',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Arzoo Nasarabadi',
    presidentName: 'Lucas Farmer',
    presidentEmail: 'farmer4501@mydusd.org',
    email: 'farmer4501@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-204',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '27',
    name: 'DHS Poetry',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Brandon Youngsma',
    presidentName: 'Prisha Viswanadha',
    presidentEmail: 'viswanadha4696@mydusd.org',
    email: 'viswanadha4696@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-203',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '28',
    name: 'DHS Psychology Club',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Jessica Russell',
    presidentName: 'Radhika Mathur & Brianna Huang',
    presidentEmail: 'mathur8269@mydusd.org',
    email: 'mathur8269@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-103',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '29',
    name: 'DHS Quantum Computing Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Daniel Olivas',
    presidentName: 'Anay Chokhani',
    presidentEmail: 'chokhani0958@mydusd.org',
    email: 'chokhani0958@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-104',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '30',
    name: 'DHS Spikeball Club',
    description: '',
    category: 'Sports' as ClubCategory,
    tags: [],
    advisorName: 'Juliana Bremer',
    presidentName: 'Alivia Farmer',
    presidentEmail: 'farmer4500@mydusd.org',
    email: 'farmer4500@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-212',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '31',
    name: 'DHS Technical Theater Club',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Edward Hightower',
    presidentName: 'Rachana Paladugu, Caitlyn Wong',
    presidentEmail: 'paladugu4269@mydusd.org',
    email: 'paladugu4269@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'PAC Lobby',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '32',
    name: 'DHS Women in STEM',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Matt Janisch',
    presidentName: 'Mahi Dalal',
    presidentEmail: 'dalal1478@mydusd.org',
    email: 'dalal1478@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-112',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '33',
    name: 'Drama Club',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Edward Hightower',
    presidentName: 'Rishan Sathiyaa',
    presidentEmail: 'sathiyaa6756@mydusd.org',
    email: 'sathiyaa6756@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'C-116',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '34',
    name: 'Dublin Afsana',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Michael Correia',
    presidentName: 'Aadhya Bogadi (Captain)',
    presidentEmail: 'bogadi8183@mydusd.org',
    email: 'bogadi8183@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-203',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '35',
    name: 'Dublin Badminton Club',
    description: '',
    category: 'Sports' as ClubCategory,
    tags: [],
    advisorName: 'Amy Lopez',
    presidentName: 'Kristie Leung',
    presidentEmail: 'leung4104@mydusd.org',
    email: 'leung4104@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: 'Every Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'Old Gym',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '36',
    name: 'Dublin Computer Science Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Scott Wojacynski',
    presidentName: 'Kaushik Chadolu',
    presidentEmail: 'chandolu2897@mydusd.org',
    email: 'chandolu2897@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-110',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '37',
    name: 'Dublin DECA',
    description: '',
    category: 'Business' as ClubCategory,
    tags: [],
    advisorName: 'Bailey Udoutch',
    presidentName: 'Ekam Dhot',
    presidentEmail: 'dhot8379@mydusd.org',
    email: 'dhot8379@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'F-206',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '38',
    name: 'Dublin High Mock Trial',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Jeff Taylor',
    presidentName: 'Harveer Saini',
    presidentEmail: 'saini8304@mydusd.org',
    email: 'saini8304@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: 'Every Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-108',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '39',
    name: 'Dublin High School Speech & Debate',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Nathaniel Grim',
    presidentName: 'Harveer Saini',
    presidentEmail: 'saini8304@mydusd.org',
    email: 'saini8304@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-202',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '40',
    name: 'Dublin High School Two Birds Club',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Kelly Aguiar',
    presidentName: 'Manlika Pal',
    presidentEmail: 'pal3274@mydusd.org',
    email: 'pal3274@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-101',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '41',
    name: 'Dublin Interact',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Shannon Persley',
    presidentName: 'Siqi Li',
    presidentEmail: 'li3647@mydusd.org',
    email: 'li3647@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'N-107',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '42',
    name: 'Dublin Living Outside',
    description: '',
    category: 'Hobbies' as ClubCategory,
    tags: [],
    advisorName: 'Kate Maurer',
    presidentName: 'Kartheeka Namburu',
    presidentEmail: 'namburu2654@mydusd.org',
    email: 'namburu2654@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-202',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '43',
    name: 'Dublin MEDLIFE',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Kelly Gambs',
    presidentName: 'Avantika Raavi & Shruthi Valliappan',
    presidentEmail: 'raavi5600@mydusd.org',
    email: 'raavi5600@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-203',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '44',
    name: 'Dublin UNICEF',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Rich Hernandez',
    presidentName: 'Aadhya Bogadi',
    presidentEmail: 'bogadi8183@mydusd.org',
    email: 'bogadi8183@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-111',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '45',
    name: 'Dungeons and Dragons Club',
    description: '',
    category: 'Hobbies' as ClubCategory,
    tags: [],
    advisorName: 'Mitchell Kless',
    presidentName: 'Cameron Genest',
    presidentEmail: 'genest7813@mydusd.org',
    email: 'genest7813@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: 'Every Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-205',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '46',
    name: 'Economics and Technology Society',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Alissa Power',
    presidentName: 'Jaanya Gupta and Bea Rarangol',
    presidentEmail: 'rarangol9163@mydusd.org',
    email: 'rarangol9163@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-101',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '47',
    name: 'Engineering Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Eugene Chou',
    presidentName: 'Temuulen Burrows',
    presidentEmail: 'burrows5333@mydusd.org',
    email: 'burrows5333@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'F-103',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '48',
    name: 'FCCLA',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Slavec Nichole',
    presidentName: 'Amy Moreno-Luna',
    presidentEmail: 'morenoluna1262@mydusd.org',
    email: 'morenoluna1262@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Wednesday',
    meetingTime: '3:00 PM',
    meetingLocation: 'H-07',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '49',
    name: 'Filipino American Student Union (FASU)',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Trevor Johnston',
    presidentName: 'Kheandra Suarez',
    presidentEmail: 'suarez3466@mydusd.org',
    email: 'suarez3466@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: 'Every Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-202',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '50',
    name: "Filmmaker's Club",
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Martin Glickman',
    presidentName: 'Christian Campbell',
    presidentEmail: 'campbell5712@mydusd.org',
    email: 'campbell5712@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: 'Every Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'C-121',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '51',
    name: 'Financial Literacy Club',
    description: '',
    category: 'Business' as ClubCategory,
    tags: [],
    advisorName: 'Nadine Medeiros',
    presidentName: 'Veera Desale',
    presidentEmail: 'desale4971@mydusd.org',
    email: 'desale4971@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-107',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '52',
    name: 'French Club',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Claude Isaac',
    presidentName: 'Anishka Vora',
    presidentEmail: 'vora3237@mydusd.org',
    email: 'vora3237@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-101',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '53',
    name: 'Friends in Serving Him (FISH) Club',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Dan Arnold',
    presidentName: 'Jayden Lee',
    presidentEmail: 'lee5472@mydusd.org',
    email: 'lee5472@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: 'Every Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-111',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '54',
    name: 'Gender Sexuality Alliance',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Claire Yackley',
    presidentName: 'Emaan Qayyum',
    presidentEmail: 'qayyum1361@mydusd.org',
    email: 'qayyum1361@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'C-120',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '55',
    name: 'Generation Code',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Jasneet Matta',
    presidentName: 'Veer Gill, Jayden Lee',
    presidentEmail: 'gill4890@mydusd.org',
    email: 'gill4890@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'F-105',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '56',
    name: 'Girls Who Code',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Emily Hurd',
    presidentName: 'Alicia Wang',
    presidentEmail: 'wang0838@mydusd.org',
    email: 'wang0838@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-108',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '57',
    name: 'Girls4Sports',
    description: '',
    category: 'Sports' as ClubCategory,
    tags: [],
    advisorName: 'Bidjan Aminian',
    presidentName: 'Shreeya Rao Lalam, Arshia Singh',
    presidentEmail: 'lalam4994@mydusd.org',
    email: 'lalam4994@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-104',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '58',
    name: 'Heartfelt Connections Club',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Hae Sol Park',
    presidentName: 'Chenxi (Michelle) Dou',
    presidentEmail: 'dou2662@mydusd.org',
    email: 'dou2662@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-104',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '59',
    name: 'HOSA',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Julianne Sundstrom',
    presidentName: 'Charlotte Ho',
    presidentEmail: 'ho3468@mydusd.org',
    email: 'ho3468@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'F-208 or F-305',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '60',
    name: 'Improv Club',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Edward Hightower',
    presidentName: 'Rishan Sathiyaa',
    presidentEmail: 'sathiyaa6756@mydusd.org',
    email: 'sathiyaa6756@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'C-116',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '61',
    name: 'Indian Student Association',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Nathaniel Grim',
    presidentName: 'Prisha Ayachit',
    presidentEmail: 'ayachit4591@mydusd.org',
    email: 'ayachit4591@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-202',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '62',
    name: 'Key Club',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Ashley Sheaff',
    presidentName: 'Nidzenrah "Calyx" Pacio',
    presidentEmail: 'pacio3208@mydusd.org',
    email: 'pacio3208@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-213',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '63',
    name: 'Kindness Bracelets Club',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Kendon Matkins',
    presidentName: 'Lucy Lagrone',
    presidentEmail: 'lagrone0456@mydusd.org',
    email: 'lagrone0456@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-109',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '64',
    name: 'Latinos Unidos',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Jennifer Ibarria-Gonzalez',
    presidentName: 'Vanessa Torrano',
    presidentEmail: 'torrano3241@mydusd.org',
    email: 'torrano3241@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-104',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '65',
    name: 'Music Matters',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Jack Bainton',
    presidentName: 'Yena Lee',
    presidentEmail: 'lee1208@mydusd.org',
    email: 'lee1208@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'C-119',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '66',
    name: 'Muslim Student Association',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Ramany Kaplan',
    presidentName: 'Minaal Mokarim',
    presidentEmail: 'mokarim0944@mydusd.org',
    email: 'mokarim0944@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Thursday; switches to 1st and 3rd Friday, 2nd and 4th Friday during daylight savings',
    meetingTime: 'Lunch',
    meetingLocation: 'L-206',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '67',
    name: 'NAMI (National Alliance against Mental Illness)',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Ramany Kaplan',
    presidentName: 'Tanush Gaur',
    presidentEmail: 'gaur4987@mydusd.org',
    email: 'gaur4987@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-206',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '68',
    name: 'National Honor Society',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Neilson Vuong',
    presidentName: 'Cynthia Lin',
    presidentEmail: 'lin3223@mydusd.org',
    email: 'lin3223@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'Library and L-204',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '69',
    name: 'National Honor Society for Dance Arts',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Lauren deLucia',
    presidentName: 'Mia Starczewski',
    presidentEmail: 'starczewski3224@mydusd.org',
    email: 'starczewski3224@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'E-3',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '70',
    name: 'Neuroscience Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Jaclyn Capie',
    presidentName: 'Sofia Kukricar, Viviana Andrade',
    presidentEmail: 'kukricar8436@mydusd.org',
    email: 'kukricar8436@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-102',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '71',
    name: 'NYLA',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Claude Isaac',
    presidentName: 'Siddh Rajrishi',
    presidentEmail: 'rajrishi4043@mydusd.org',
    email: 'rajrishi4043@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-101',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '72',
    name: 'Physics Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Audrey Xu',
    presidentName: 'Moon Liu',
    presidentEmail: 'liu4390@mydusd.org',
    email: 'liu4390@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-103',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '73',
    name: 'Poverty Patch-Up',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Carmen Chan',
    presidentName: 'Shivani Ramanathan',
    presidentEmail: 'ramanathan1359@mydusd.org',
    email: 'ramanathan1359@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-208',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '74',
    name: "Psychology's Stage",
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Shannon Smoot',
    presidentName: 'Sristi (Cesi) Malhotra',
    presidentEmail: 'malhotra6817@mydusd.org',
    email: 'malhotra6817@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'Library',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '75',
    name: 'Red Cross Club',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Jennifer Angel-Diaz',
    presidentName: 'Krista Chen',
    presidentEmail: 'chen2874@mydusd.org',
    email: 'chen2874@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-209',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '76',
    name: 'Rehab Rescue',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Raj Ramchandani',
    presidentName: 'Mahi Patel',
    presidentEmail: 'patel5462@mydusd.org',
    email: 'patel5462@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-207',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '77',
    name: "Rubik's Cube Club",
    description: '',
    category: 'Hobbies' as ClubCategory,
    tags: [],
    advisorName: 'Sarah Ledford',
    presidentName: 'Adhi Jeyappragash',
    presidentEmail: 'jeyappragash2876@mydusd.org',
    email: 'jeyappragash2876@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-111',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '78',
    name: 'S4T (Students 4 Tutors)',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Allison Malone',
    presidentName: 'Jihu Kim',
    presidentEmail: 'Kim4962@mydusd.org',
    email: 'Kim4962@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-209',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '79',
    name: 'Science for the Bay',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Warren Parker',
    presidentName: 'Neal Mann',
    presidentEmail: 'mann7175@mydusd.org',
    email: 'mann7175@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'Counseling Office',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '80',
    name: 'Science Olympiad Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Isaiah Mohr',
    presidentName: 'Kylie Wong',
    presidentEmail: 'wong2929@mydusd.org',
    email: 'wong2929@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-207',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '81',
    name: 'Slavic Culture Club',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Elena Tigner',
    presidentName: 'Sofiia Predchenko',
    presidentEmail: 'predchenko1741@mydusd.org',
    email: 'predchenko1741@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-208',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '82',
    name: 'Sociedad Honoraria Hispánica',
    description: '',
    category: 'Academic' as ClubCategory,
    tags: [],
    advisorName: 'Jennifer Ibarria-Gonzalez',
    presidentName: 'Haziq Ahmed',
    presidentEmail: 'ahmed1098@mydusd.org',
    email: 'ahmed1098@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-104',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '83',
    name: 'Stemprenuer Club',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Daniel Olivas',
    presidentName: 'Riya, Kelly, Madi',
    presidentEmail: 'singh5197@mydusd.org',
    email: 'singh5197@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-104',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '84',
    name: 'Student Climate Corps',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Isaiah Mohr',
    presidentName: 'Tarun Rajesh',
    presidentEmail: 'rajesh1685@mydusd.org',
    email: 'rajesh1685@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'K-207',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '85',
    name: 'Student Health Advocates for a Positive Environment (SHAPE)',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Anne Ha',
    presidentName: 'Kylene Wong',
    presidentEmail: 'wong3605@mydusd.org',
    email: 'wong3605@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'F-305',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '86',
    name: 'Swab4Dublin',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Raj Ramachandani',
    presidentName: 'Anoushka Malhotra',
    presidentEmail: 'malhotra1457@mydusd.org',
    email: 'malhotra1457@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-207',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '87',
    name: 'SWENext',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Brian Schick',
    presidentName: 'Kopal Tare & Shrinidhi Rudrashetty',
    presidentEmail: 'tare0970@mydusd.org',
    email: 'tare0970@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'F-101',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '88',
    name: 'Swift-as-lit',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Brandon Youngsma',
    presidentName: 'Zaynab Mohammed',
    presidentEmail: 'mohammed6183@mydusd.org',
    email: 'mohammed6183@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-203',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '89',
    name: 'Taekwondo Club',
    description: '',
    category: 'Sports' as ClubCategory,
    tags: [],
    advisorName: 'Logan Calhoun',
    presidentName: 'Daniel Ibarria, Aidan Ng',
    presidentEmail: 'ibarria4930@mydusd.org',
    email: 'ibarria4930@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Wednesday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-205',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '90',
    name: 'Taiwanese Student Association',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Mary Hake',
    presidentName: 'Austin Lu',
    presidentEmail: 'austinlu8@gmail.com',
    email: 'austinlu8@gmail.com',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-109',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '91',
    name: 'The Black Student Union',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Warren Parker',
    presidentName: 'Haili Smith, Sitara Spivey',
    presidentEmail: 'Spivey7668@mydusd.org',
    email: 'Spivey7668@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-213',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '92',
    name: 'The Finance Circle',
    description: '',
    category: 'Business' as ClubCategory,
    tags: [],
    advisorName: 'John Parsons',
    presidentName: 'Jadon Rybak',
    presidentEmail: 'rybak3414@mydusd.org',
    email: 'rybak3414@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-211',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '93',
    name: 'The Her Mind Project',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Kiley Dinis',
    presidentName: 'Anika Panicker, Baani Gupta',
    presidentEmail: 'gupta1399@mydusd.org',
    email: 'gupta1399@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'M-201',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '94',
    name: 'Trading Card Club',
    description: '',
    category: 'Hobbies' as ClubCategory,
    tags: [],
    advisorName: 'Mitchell Kless',
    presidentName: 'Cameron Genest',
    presidentEmail: 'Genest7813@mydusd.org',
    email: 'Genest7813@mydusd.org',
    meetingFrequency: 'Weekly' as const,
    meetingDay: '1st and 3rd Wednesday, 2nd and 4th Wednesday, 1st and 3rd Friday, 2nd and 4th Friday',
    meetingTime: 'Lunch',
    meetingLocation: 'J-205',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '95',
    name: 'Tri-M Music Honors Society',
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Jack Bainton',
    presidentName: 'Trisha Bhattacharya & Cathy Chen',
    presidentEmail: 'bhattacharya2848@mydusd.org',
    email: 'bhattacharya2848@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'C-119',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '96',
    name: 'TUPE (Tobacco Usage Peer Educators)',
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Holly Garcia',
    presidentName: 'Hasini Dontula',
    presidentEmail: 'dontula1323@mydusd.org',
    email: 'dontula1323@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'H-6',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '97',
    name: 'Vietnamese Student Association',
    description: '',
    category: 'Cultural' as ClubCategory,
    tags: [],
    advisorName: 'Mary Hake',
    presidentName: 'Zoey Tran and Lac-Anh Nguyen',
    presidentEmail: 'tran2392@mydusd.org',
    email: 'tran2392@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '2nd and 4th Thursday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-109',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '98',
    name: "Voices For Alzheimer's",
    description: '',
    category: 'Community Service' as ClubCategory,
    tags: [],
    advisorName: 'Logan Calhoun',
    presidentName: 'Ekagra Dwivedi',
    presidentEmail: 'dwivedi5921@mydusd.org',
    email: 'dwivedi5921@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-205',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '99',
    name: "Writers' Club",
    description: '',
    category: 'Arts' as ClubCategory,
    tags: [],
    advisorName: 'Carmen Chan',
    presidentName: 'Aryan Panigrahi, Ashton Lu',
    presidentEmail: 'panigrahi2992@mydusd.org',
    email: 'panigrahi2992@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Monday',
    meetingTime: 'Lunch',
    meetingLocation: 'L-208',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  },
  {
    id: '100',
    name: 'Young Innovators',
    description: '',
    category: 'STEM' as ClubCategory,
    tags: [],
    advisorName: 'Nicole Slavec',
    presidentName: 'Susmita Vissapragada',
    presidentEmail: 'vissapragada8130@mydusd.org',
    email: 'vissapragada8130@mydusd.org',
    meetingFrequency: 'Bi-weekly' as const,
    meetingDay: '1st and 3rd Tuesday',
    meetingTime: 'Lunch',
    meetingLocation: 'H-7',
    imageUrl: null,
    memberCount: 0,
    yearFounded: 0,
    upcomingMeetings: [],
    socialMedia: {},
    events: [],
    portfolios: []
  }
];

export const getAllClubsProcedure = publicProcedure.query(() => {
  return REAL_CLUBS_DATA;
});